apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
  namespace: kagent
type: Opaque
data:
  api-key: c2stcHJvai05R1dzY29IVk83b21ZOGF0ZHZvdlVLU2R4WElCWHNfQUFIR2g4Y05HYWtSMTVfMGxhZmRyYzJmUHNTQXF5WXFKaXY5YjV5TnRKT1QzQmxia0ZKM1BkbWR3X1VQXzZ6bEpzX1RDZHFGMk1wM0h6TzBwWlZremE3a2RPa2tXS1IyeDNYcHFuTlRNczVHRlBlR0hQbFBuZXFsbkNyOEE=
