apiVersion: v1
kind: Service
metadata:
  name: mcp
  namespace: kagent
  labels:
    app: mcp
spec:
  type: NodePort
  selector:
    app: mcp
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
      protocol: TCP
      name: http
