apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: kagent-api
  namespace: kagent
spec:
  description: 'Kagent API Tool Server'
  config:
    sse:
      url: 'http://kagent.kagent.svc.cluster.local:8081/api/mcp/sse'
      timeout: '30s'
      sse_read_timeout: '30s'
